name: Deploy to NetSuite

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install SuiteCloud CLI
        run: npm install -g @oracle/suitecloud-cli --acceptsuitecloudsdklicense

      - name: Install SuiteCloud CLI
        run: npm install -g @oracle/suitecloud-cli --acceptsuitecloudsdklicense

      - name: Deploy to Training
        env:
          SDF_ACCOUNT: ${{ secrets.NETSUITE_ACCOUNT }}
          SDF_ROLE: ${{ secrets.NETSUITE_ROLE }}
          SDF_EMAIL: ${{ secrets.NETSUITE_EMAIL }}
          SDF_PASSWORD: ${{ secrets.NETSUITE_PASSWORD }}
          SDF_APPLICATION_ID: ${{ secrets.NETSUITE_APP_ID }}
        run: |
          suitecloud account:manageauth --authid github-action --account $SDF_ACCOUNT --role $SDF_ROLE --email $SDF_EMAIL --password $SDF_PASSWORD --applicationId $SDF_APPLICATION_ID
          suitecloud project:deploy --authid github-action
