name: Deploy to NetSuite

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install SuiteCloud CLI
        run: npm install -g @oracle/suitecloud-cli --acceptsuitecloudsdklicense

      - name: Install SuiteCloud CLI
        run: npm install -g @oracle/suitecloud-cli --acceptsuitecloudsdklicense

      - name: Deploy to Training
        env:
          NS_ACCOUNT: ${{ secrets.NETSUITE_ACCOUNT }}
          NS_EMAIL: ${{ secrets.NETSUITE_EMAIL }}
          NS_PASSWORD: ${{ secrets.NETSUITE_TOKEN_ID }}
          NS_ROLEID: ${{ secrets.NETSUITE_ROLE }}
          NS_APPID: ${{ secrets.NETSUITE_TOKEN_SECRET }}
        run: |
              authenticateci [-account AccountId]  
              [-authid AuthId]
              [-certificateid CertificateId]
              [-privatekeypath PrivateKeyPath]
              [-url NetSuiteDomainURL] 
